FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml ./

RUN pip install --no-cache-dir uv \
    && uv venv .venv

COPY . .

RUN uv pip install .

EXPOSE 8000

CMD [".venv/bin/python", "-m", "litestar", "--app-dir", "src", "--app", "api.backend:app", "run"]
