services:
  postgres:
    image: postgres:15
    container_name: qnnas-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: qnnas
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
